# language: node_js
# node_js:
#   - "5"
#   - "6"
# after_success:
#   - 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'

deploy:
  provider: script
  skip_cleanup: true
  script: scripts/release.sh
  on:
    node: "6"
    branches:
      only:
        - master
        - dev
